---
title: "Quantifying creativity through repository mining"
author: "J. J. Merelo"
date: "13 de agosto de 2016"
output: html_document
abstract: |
  This is a template for reporting on the characteristics of the changes in a project from using the number of lines changed in every commit that affects those files. Our intention, by analyzing repositories that hold projects of different type such as books, research papers or simply software, is to show that they present remarkably similar characteristics, main diferences based on the fact that they are collaborative or not and the number of commits present.
  In this report we will visualize change size in different ways.
---

```{r setup, include=FALSE}
library(ggplot2)
library("ggfortify")
library(dplyr)
lines <- read.csv("../data/books/lines_hoborg_text_text_md.csv")
```

## Summary




```{r summary}
summary(lines)
```

## Including Plots

You can also embed plots, for example:

```{r timeline, echo=FALSE}
gg.lines = ggplot(lines)
gg.lines+geom_point(aes(x=row.names(lines),y=Lines.changed))
gg.lines+geom_line(aes(x=row.names(lines),y=Lines.changed,group=1))
gg.lines+geom_point(aes(x=row.names(lines),y=Lines.changed))+scale_y_log10()
gg.lines+geom_line(aes(x=row.names(lines),y=Lines.changed,group=1))+scale_y_log10()
```

```{r linecount, echo=FALSE}
by.lines <- group_by(lines,Lines.changed)
lines.count <- summarize(by.lines, count=n())
ggplot(lines.count, aes(x=Lines.changed, y=count))+geom_point()+scale_x_log10()+scale_y_log10()
```

```{r autocorrelation, echo=FALSE}
autoplot(pacf(lines$Lines.changed, plot=FALSE) )
```

```{r powerlaw, echo=FALSE}
ggplot(data=lines, aes(lines$Lines.changed)) + geom_histogram(bins=100)+scale_x_log10()
sorted.lines <- data.frame(x=1:length(lines$Lines.changed),Lines.changed=as.numeric(lines[order(-lines$Lines.changed),]))
ggplot()+geom_point(data=sorted.lines,aes(x=x,y=Lines.changed))
ggplot()+geom_point(data=sorted.lines,aes(x=x,y=Lines.changed))+scale_y_log10()
```
