library(ggplot2)
library("ggfortify")
lines <- read.csv("../data/books/lines_hoborg_text_text_md.csv")
summary(lines)
ggplot()+geom_point(data=lines,aes(x=row.names(lines),y=Lines.changed))
ggplot()+geom_line(data=lines,aes(x=row.names(lines),y=Lines.changed,group=1))
ggplot()+geom_point(data=lines,aes(x=row.names(lines),y=Lines.changed))+scale_y_log10()
ggplot()+geom_line(data=lines,aes(x=row.names(lines),y=Lines.changed,group=1))+scale_y_log10()
autoplot(pacf(lines$Lines.changed, plot=FALSE) )
ggplot(data=lines, aes(lines$Lines.changed)) + geom_histogram(bins=100)+scale_x_log10()
sorted.lines <- data.frame(x=1:length(lines$Lines.changed),Lines.changed=as.numeric(lines[order(-lines$Lines.changed),]))
ggplot()+geom_point(data=sorted.lines,aes(x=x,y=Lines.changed))
ggplot()+geom_point(data=sorted.lines,aes(x=x,y=Lines.changed))+scale_y_log10()
